---
  - become: true
    gather_facts: true
    hosts: all
    name: Converge
    roles:
      - role: buluma.security
        security_autoupdate_enabled: false
        security_fail2ban_enabled: false
