---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.package:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Ensure build dependencies are installed (RedHat).
      ansible.builtin.package:
        name:
          - openssh-server
          - openssh-clients
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Ensure build dependencies are installed (Fedora).
      ansible.builtin.package:
        name: procps
        state: present
      when: ansible_distribution == 'Fedora'

    - name: Ensure build dependencies are installed (Debian).
      ansible.builtin.package:
        name:
          - openssh-server
          - openssh-client
        state: present
      when: ansible_os_family == 'Debian'

    - name: Ensure auth.log file is present.
      ansible.builtin.copy:
        dest: /var/log/auth.log
        content: ""
        force: false
        mode: 0644
      when: ansible_distribution == 'Debian'

  roles:
    - role: geerlingguy.security
