---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: ansible-role-security
      security_autoupdate_enabled: false
      security_fail2ban_enabled: false  # TODO: Check fail2ban failure on focal/bionic
