---
#
# Ansible managed
#

name: Ansible Molecule

on:
  # Schedule updates (once daily)
  schedule:
    - cron: '37 19 * * *'
  workflow_dispatch:
  push: {branches: ["master", "main", "testing"]}

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: buluma/molecule-action@v4.0.6
        with:
          command: lint
  test:
    needs:
      - lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - image: "enterpriselinux"
            tag: "7"
          - image: "enterpriselinux"
            tag: "latest"
          - image: "centos"
            tag: "centos8"
          - image: "centos"
            tag: "centos7"
          - image: "debian-systemd"
            tag: "latest"
          - image: "debian-systemd"
            tag: "bookworm"
          - image: "debian"
            tag: "jessie"
          - image: "debian"
            tag: "sid"
          - image: "debian"
            tag: "bullseye"
          - image: "debian"
            tag: "stretch"
          - image: "debian"
            tag: "bookworm"
          - image: "debian"
            tag: "buster"
          - image: "ubuntu"
            tag: "jammy"
          - image: "ubuntu"
            tag: "xenial"
          - image: "ubuntu"
            tag: "hirsute"
          - image: "ubuntu"
            tag: "bionic"
          - image: "ubuntu"
            tag: "impish"
          - image: "ubuntu"
            tag: "focal"
          - image: "amazonlinux"
            tag: "2"
          - image: "fedora"
            tag: "latest"
          - image: "fedora"
            tag: "rawhide"
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - name: disable apparmor for mysql
        run: sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
      - name: parse apparmor for mysql
        run: sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      - name: molecule
        uses: buluma/molecule-action@v4.0.6
        with:
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
